/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/renderer/components/app/AboutModal.vue')['default']
    AboutView: typeof import('./src/renderer/components/AboutView.vue')['default']
    AppModalShell: typeof import('./src/renderer/components/app/AppModalShell.vue')['default']
    AppNavigation: typeof import('./src/renderer/components/AppNavigation.vue')['default']
    AppShell: typeof import('./src/renderer/layouts/AppShell.vue')['default']
    AuthenticatedFrame: typeof import('./src/renderer/components/app/AuthenticatedFrame.vue')['default']
    AuthenticatedUserMenu: typeof import('./src/renderer/components/app/AuthenticatedUserMenu.vue')['default']
    AuthForm: typeof import('./src/renderer/components/auth/AuthForm.vue')['default']
    AuthGate: typeof import('./src/renderer/components/auth/AuthGate.vue')['default']
    AuthInitState: typeof import('./src/renderer/components/auth/AuthInitState.vue')['default']
    BuiltinToolSettingsView: typeof import('./src/renderer/components/settings/BuiltinToolSettingsView.vue')['default']
    ChatConversationView: typeof import('./src/renderer/components/chat/ChatConversationView.vue')['default']
    ChatInputPanel: typeof import('./src/renderer/components/chat/ChatInputPanel.vue')['default']
    ChatModelSwitcher: typeof import('./src/renderer/components/chat/ChatModelSwitcher.vue')['default']
    ChatNewConversationView: typeof import('./src/renderer/components/chat/ChatNewConversationView.vue')['default']
    ConversationSidebar: typeof import('./src/renderer/components/chat/ConversationSidebar.vue')['default']
    HomeView: typeof import('./src/renderer/components/HomeView.vue')['default']
    LocaleSwitcher: typeof import('./src/renderer/components/LocaleSwitcher.vue')['default']
    McpSettingsView: typeof import('./src/renderer/components/settings/McpSettingsView.vue')['default']
    MessageBubble: typeof import('./src/renderer/components/chat/MessageBubble.vue')['default']
    ProviderSettingsModal: typeof import('./src/renderer/components/providers/ProviderSettingsModal.vue')['default']
    ProviderSettingsView: typeof import('./src/renderer/components/providers/ProviderSettingsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuntimeBridgeCard: typeof import('./src/renderer/components/RuntimeBridgeCard.vue')['default']
    SettingsModal: typeof import('./src/renderer/components/settings/SettingsModal.vue')['default']
    SkillSettingsView: typeof import('./src/renderer/components/settings/SkillSettingsView.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
