/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<
      'index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'auth': RouteRecordInfo<
      'auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chat': RouteRecordInfo<
      'chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | '/chat/'
      | '/chat/[id]'
    >,
    '/chat/': RouteRecordInfo<
      '/chat/',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat/[id]': RouteRecordInfo<
      '/chat/[id]',
      '/chat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/renderer/pages/index.vue': {
      routes:
        | 'index'
      views:
        | never
    }
    'src/renderer/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/renderer/pages/auth.vue': {
      routes:
        | 'auth'
      views:
        | never
    }
    'src/renderer/pages/chat.vue': {
      routes:
        | '/chat/'
        | '/chat/[id]'
        | 'chat'
      views:
        | 'default'
    }
    'src/renderer/pages/chat/index.vue': {
      routes:
        | '/chat/'
      views:
        | never
    }
    'src/renderer/pages/chat/[id].vue': {
      routes:
        | '/chat/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
